import React, {useMemo, useState} from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, BadgeDollarSign, Building2, CheckCircle2, Mail, Phone, QrCode, Search, ShieldCheck, Sparkles, Zap } from 'lucide-react';
import './styles.css';
const suppliers = ['Constellation', 'Direct Energy', 'ENGIE', 'NRG', 'Shell Energy', 'Local utility suppliers'];
function money(n){return n.toLocaleString(undefined,{maximumFractionDigits:0});}
function App(){
  const [monthlySpend,setMonthlySpend]=useState(8500); const [currentRate,setCurrentRate]=useState(0.124); const [expectedRate,setExpectedRate]=useState(0.109);
  const estimate=useMemo(()=>{ const annual=monthlySpend*12; const pct=Math.max(0,(currentRate-expectedRate)/currentRate); return {annual,pct,savings:annual*pct}; },[monthlySpend,currentRate,expectedRate]);
  return <main>
    <nav className="nav"><div className="brand"><span className="brandMark"><Zap size={15}/></span> Power Procurement</div><div className="navLinks"><a href="#auction">Reverse auction</a><a href="#savings">Savings estimate</a><a href="#outreach">100-card pilot</a></div><a className="navCta" href="#lead-form">Check my rate</a></nav>
    <section className="hero"><div className="heroGrid"><div className="heroCopy"><div className="eyebrow"><Sparkles size={14}/> Free procurement check for high-usage businesses</div><h1>Let energy suppliers compete for your gas and electric account.</h1><p className="subtitle">Power Procurement helps businesses compare their current utility rate against bids from qualified suppliers in their service area using a reverse auction through Power Kiosk.</p><div className="ctaRow"><a className="primary" href="#lead-form">Estimate savings <ArrowRight size={16}/></a><a className="secondary" href="#auction">How it works</a></div><div className="trustRow"><CheckCircle2 size={16}/> No supplier change unless the bid is better. Jeremy is compensated by commission when a successful account is placed.</div></div><div className="heroCard"><div className="cardTop"><span>Reverse auction preview</span><span className="live">LIVE BIDS</span></div>{suppliers.slice(0,5).map((s,i)=><div className="bid" key={s}><div><strong>{s}</strong><small>{i===0?'Lowest qualified bid':'Supplier bid received'}</small></div><span className={i===0?'best':''}>${(expectedRate+i*.004).toFixed(3)}/kWh</span></div>)}<div className="winner"><BadgeDollarSign size={18}/><div><strong>Projected savings</strong><small>${money(estimate.savings)} / year based on your inputs</small></div></div></div></div></section>
    <section className="logoBand"><span>restaurants</span><span>manufacturers</span><span>warehouses</span><span>multi-site retail</span><span>large offices</span></section>
    <section id="auction" className="section"><div className="sectionHeader"><span className="kicker">Reverse auction</span><h2>A simple process: collect the bill, invite suppliers, select the lowest qualified bid.</h2></div><div className="steps"><div className="step"><Search/><h3>1. Check the current rate</h3><p>We collect the business’s current energy rate, usage profile, utility territory, and contract timing.</p></div><div className="step"><Building2/><h3>2. Invite local suppliers</h3><p>Through Power Kiosk, qualified suppliers in the account’s area are invited to compete for the business.</p></div><div className="step"><BadgeDollarSign/><h3>3. Run the auction</h3><p>Suppliers bid down the rate. The business can select the lowest qualified offer when it beats the current cost.</p></div><div className="step"><ShieldCheck/><h3>4. Keep the upside</h3><p>The customer saves money; Jeremy earns a commission for sourcing and placing the account.</p></div></div></section>
    <section id="savings" className="calculator"><div><span className="kicker">Savings estimator</span><h2>Give buyers a first step before the call.</h2><p>This landing page is designed to be the QR destination on a direct-mail postcard. A buyer can plug in their rough spend and rate, then Jeremy follows up with the warmest responders.</p></div><div className="calcCard"><label>Monthly gas/electric spend <span>${money(monthlySpend)}</span></label><input type="range" min="1000" max="50000" step="500" value={monthlySpend} onChange={e=>setMonthlySpend(Number(e.target.value))}/><label>Current blended rate <span>${currentRate.toFixed(3)}</span></label><input type="range" min="0.07" max="0.25" step="0.001" value={currentRate} onChange={e=>setCurrentRate(Number(e.target.value))}/><label>Estimated winning bid <span>${expectedRate.toFixed(3)}</span></label><input type="range" min="0.06" max="0.23" step="0.001" value={expectedRate} onChange={e=>setExpectedRate(Number(e.target.value))}/><div className="result"><small>Estimated annual savings</small><strong>${money(estimate.savings)}</strong><span>{Math.round(estimate.pct*100)}% below current rate</span></div></div></section>
    <section id="outreach" className="section dark"><div className="sectionHeader"><span className="kicker">Direct mail strategy</span><h2>Send 100 postcards, track QR opens, call the warm 20% first.</h2><p>Jeremy’s lead protocol can keep finding high-usage businesses every Wednesday, Thursday, and Friday. The mail API turns that list into physical QR-code postcards that point back to this page.</p></div><div className="campaignGrid"><div><QrCode/><h3>Personalized QR page</h3><p>Each postcard can include a unique QR link so Jeremy knows which company scanned the offer.</p></div><div><Mail/><h3>Free savings check offer</h3><p>“I built a free application that checks whether your power costs can be lowered by supplier competition.”</p></div><div><Phone/><h3>Prioritized follow-up</h3><p>If 20 of 100 scan the QR code, Jeremy calls those 20 first instead of cold-calling the whole list.</p></div></div></section>
    <section id="lead-form" className="lead"><div className="leadBox"><span className="kicker">For buyers</span><h2>Want to see if your business can lower its energy costs?</h2><p>Send a recent bill or enter your rough rate. We’ll compare your current cost against supplier competition and show whether a reverse auction is worth running.</p><form onSubmit={(e)=>{e.preventDefault(); alert('Demo only: connect this form to CRM/email before launch.')}}><input placeholder="Business name" /><input placeholder="Email" /><input placeholder="Monthly utility spend" /><button>Request free savings check</button></form><small>Demo landing page — final production version should connect to CRM, email alerts, and QR/postcard tracking.</small></div></section>
  </main>}
createRoot(document.getElementById('root')).render(<App/>);
